config:
  base: configs/base.yaml

seed:
  global: 42

project:
  mode: test
  experiment_name: generate_dataset_v1

episodes:
  N: 10 # number of episodes to build the dataset
  max_steps_per_episode: 500 # total number of simulation steps for a single episode
  num_workers: 4 # number of parallel CPU workers (1 = sequential)

dataset:
  save_dir: data/train # location to save dataset
  file_name: fault_identification_dataset_aux_2.npz

hpc:
  partition: CPUQ           # There's not point in using GPUs here
  time: "12:00:00" 
  ntasks: 1
  nodes: 1
  cpus_per_task: 10
  mem: 32G

  slurm_script:
    enabled: true # Launch done through a slurm file
    output_dir: slurm_files/
    job_name: demo_array

  environment:
    modules:
      - Miniconda3/24.7.1-0
    conda_env: pinn-fault-diagnosis

  launcher:
    kind: python
    command: python -m src.dataset.generator -c configs/dataset.yaml

env:
  render: false
  wind:
    angle:
      min: -3.14159
      max: 3.14159
      ornstein_uhlenbeck:
        attraction: 0.03
        amplitude: 0.05
    speed:
      min: 0.0
      max: 10.0
      ornstein_uhlenbeck:
        attraction: 0.03
        amplitude: 0.1
    info: "Be brave."

  current:
    angle:
      min: -3.14159
      max: 3.14159
      ornstein_uhlenbeck:
        attraction: 0.01
        amplitude: 0.01
    speed:
      min: 0.0
      max: 0.1
      ornstein_uhlenbeck:
        attraction: 0.01
        amplitude: 0.01
    info: "PINNs rock."

vessel:
  dt: 0.2
  dp_mode: false

  auxiliary_excitation:
    enabled: true
    # port:
    #   azimuth: 'GaussianNoise(amplitude=2.0)'
    #   speed: 'GaussianNoise(amplitude=10)'
    # starboard:
    #   azimuth: 'GaussianNoise(amplitude=2.0)'
    #   speed: 'GaussianNoise(amplitude=10)'
    port:
      azimuth: 'Sinus(frequency=0.2, amplitude=3.14159, time_delay_sec=0.0, y_offset=0.0) + GaussianNoise(amplitude=0.5)'
      speed: 'PRBS(amplitude=45, bit_rate=0.1, y_offset=45) + GaussianNoise(amplitude=10)'
    starboard:
      azimuth: 'Sinus(frequency=0.1, amplitude=-3.14159, time_delay_sec=0.0, y_offset=0.0) + GaussianNoise(amplitude=0.5)'
      speed: 'PRBS(amplitude=-45, bit_rate=0.12, y_offset=45) + GaussianNoise(amplitude=10)'

  guidance: # The guidance module generates a random trajectory to be tracked by the NMPC controller 
    d_tot: 100 # total distance for the randomly generated path
    max_turn_deg: 90 # max angle between two consecutive segment of the randomly generated path
    seg_len_range: [5, 10] # range of lengths for segment of the randomly generated path
    smooth: 3 # smoothing radius 
    target_speed:
      min: 0.3
      max: 1.0
      mean: 0.5
      std: 0.2

  navigation:
    enabled: false # false -> measurements == true states

  control:
    enabled: false   # guidance and control parameters have no effect if control is not enabled
    horizon: 30 # for MPC
    singularity_weight: 0.0

  faults:
    loss_of_effectiveness:
      prob: [0.5, 0.5, 0]
      amplitude:
        min: 0
        max: 1
        mean: 0.5 # uniform distribution if only min and max are provided, othewise clipped gaussian
        std: 0.3
      time:
        min: 0.0
        max: 1.0
        mean: 0.5
        std: 0.2

    azimuth_stucked:
      prob: [0, 0, 0] # Currently no fault
      is_integer: true # fault parameter can only be 0 or 1
      amplitude:
        min: 0
        max: 1
        mean: 1
        std: 0.2
      time:
        min: 0.0
        max: 1.0
        mean: 0.5
        std: 0.2


    